services:
  redis:
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery_worker:
    build:
      context: .
    image: celery_worker_image
    container_name: celery_worker
    command: celery -A app.workers.tasks worker --loglevel=info
    depends_on:
      - redis
    networks:
      - app_network
    environment:
      - CELERY_BROKER_URL=redis://:IlDNZ7rT1cLnjEoB767v2WH2clDuNAe1@redis-17251.c270.us-east-1-3.ec2.redns.redis-cloud.com:17251/0
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql+psycopg2://postgres:sunny@localhost:5432/github_data_test_AI_agent

networks:
  app_network:
    driver: bridge
